export enum Icon {
    Courses = "Courses",
    Copain = "Copain",
    Cuisine = "Cuisine",
    Linge = "Linge",
    Poubelle = "Poubelle",
    Sanitaires = "Sanitaires",
    Surfaces = "Surfaces",
    Default = "Défaut",
    Tasks = "Tâches",
    Historique = "Historique",
    Stats = "Stats",
    Parametres = "Parametres",
    Urgent = "Urgent",
    Add = "Ajouter",
}