name: Deploy to GitHub Pages (Simple)

on:
  push:
    branches: [ main, test-mockup ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Debug - Show context
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "Ref: ${{ github.ref }}"
          echo "Branch: ${{ github.ref_name }}"
          
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: web-app/package-lock.json

      - name: Install dependencies
        run: |
          cd web-app
          npm ci

      - name: Build application
        run: |
          cd web-app
          npm run build
          
      - name: List build output
        run: |
          echo "Build output:"
          ls -la web-app/dist/ || echo "Dist folder not found"

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: web-app/dist

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        
      - name: Show deployment URL
        run: |
          echo "Deployment URL: ${{ steps.deployment.outputs.page_url }}"